# Generated by Django 5.2.6 on 2025-09-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='service',
            name='upazila',
        ),
        migrations.AddField(
            model_name='service',
            name='duration_hours',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
