# Generated by Django 5.2.6 on 2025-09-29 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer_upazila',
        ),
    ]
